import {Suspense} from "react";
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { Canvas, events } from "@react-three/fiber";
import HeroText from "../components/HeroText";
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <Canvas
            events={events}
            antialias={true}
            linear={true}
            flat={true}
            shadows={true}
            camera={{ position: [-5, 5, -5] }}
          >
            <HeroText />
          </Canvas>
      </main>
    </>
  )
}
